# Generated by Django 2.2 on 2019-06-17 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('elderhouse', '0003_auto_20190617_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.UUIDField()),
                ('areaname', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 6, 17, 9, 33, 12, 445455, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 6, 17, 9, 33, 12, 445534, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='BathRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bath_id', models.UUIDField()),
                ('bath_medicine', models.CharField(max_length=30)),
                ('bath_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.UUIDField()),
                ('uuid', models.UUIDField()),
                ('major', models.IntegerField()),
                ('minor', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 6, 17, 9, 33, 12, 448019, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 6, 17, 9, 33, 12, 448057, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='CareType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.UUIDField()),
                ('sid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.UUIDField()),
                ('sid', models.UUIDField()),
                ('uid', models.UUIDField()),
                ('areaid', models.UUIDField()),
                ('cid', models.UUIDField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 6, 17, 9, 33, 12, 448714, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 6, 17, 9, 33, 12, 448745, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField()),
                ('uname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 6, 17, 9, 33, 12, 444539, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 6, 17, 9, 33, 12, 444570, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='ToiletRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toilet_id', models.UUIDField()),
                ('toilet_status', models.CharField(max_length=30)),
                ('toilet_amount', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 9, 33, 12, 443649, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 9, 33, 12, 443726, tzinfo=utc)),
        ),
    ]
