# Generated by Django 2.2 on 2019-06-17 09:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elderhouse', '0004_auto_20190617_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='area',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 9, 48, 33, 384154, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 9, 48, 33, 384190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 9, 48, 33, 384829, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 9, 48, 33, 384859, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resident',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resident',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 9, 48, 33, 379433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 9, 48, 33, 379514, tzinfo=utc)),
        ),
    ]
